### ISSUE TITLE
[BUG] Using named function arguments causes a panic.

### ISSUE THREAD

**Issue by FractalFir** [Cr0a3/ygen#38]
Ygen panics when compiling this snippet of Ygen IR:
```llvm
define i32 @add(i32  %a, i32  %b) {
start:
  %0 = add i32 %a, %b
  ret i32 %0
}
```
```
thread 'main' panicked at src/CodeGen/compilation/math.rs:49:1:
expected valid ls variable
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Compiler returned: 101
```
Changing the names of arguments to numbers fixes the issue.
```llvm
define i32 @add(i32 %0, i32  %1) {
start:
  %2 = add i32 %0, %1
  ret i32 %2
}
```
Since local variables can be named, I assume this should work too.
```llvm
define i32 @add(i32 %0, i32  %1) {
start:
  %c = add i32 %0, %1
  ret i32 %c
}
```

If this is not supported, then Ygen should probably print an error message(like it does in other cases).

**Comment by Cr0a3** [comment]
Thank you, this is a known issue

**Comment by Cr0a3** [comment]
@FractalFir fixed.
The fix should be online tomorrow in godbolt.

Thank you for reporting this
