### ISSUE TITLE
Whats up with the camelCase naming scheme?

### ISSUE THREAD

**Issue by advantageous-overtake** [Cr0a3/ygen#40]
I see you have #![allow(non_snake_case)] in most lib.rs files, module names are non snake case and a lot of functions are camelCase. Why? This is not idiomatic Rust and you force everybody that uses this library to have multiple naming schemes in their codebase.

**Comment by Cr0a3** [comment]
It is one week before the start of the summer break. I am not very happy about my current codegen libraries. So I start yet another one. (Hence the name).
I work much of my free time after school on it.
Months and months pass. 
Ygen gets feature richer everyday.
I mostly win the war with the bugs day over day.
Hard bugs rise (#8) it takes Weeks to fix those, but I fixed them at the end.

Then a specific individual whose name I don't want to say, asks me why I don't name it in sneak_case.

Simple answer I don't give a fuck. I just name the things how I want to on the day. Maybe it isn't as ergonomic to use. If you want them changed. Go ahead and open a pr.

Bye

**Comment by Cr0a3** [comment]
Sorry if it seems mean of aggressive
